### ISSUE TITLE
Invalid public key verification

### ISSUE THREAD

**Issue by martinpaljak** [crocs-muni/ECTester#15]
Have you tested feeding invalid public points to different cards and different methods, to see if any verification happens?

**Comment by J08nY** [comment]
Hey,
so depends on what you mean by invalid, but for most definitions we did:
 - The "invalid" test-suite tries to execute the invalid curve attack against the card/library, AFAIK all cards tested successfully reject the invalid pubkey.
 - The "degenerate" suite tries the degenerate curve attack.
 - Various other suites try corrupting the points used in various operations.

Some of these tests do lead to the cards cycling indefinitely, however these I think only happen when the corrupted points are a part of the domain parameters definition and so would fall outside many threat models. See more in this paper: https://crocs.fi.muni.cz/public/papers/primality_esorics20

**Comment by martinpaljak** [comment]
Thanks for clarification! Mostly regarding invalid curve attacks. Given my non-existent attention span, I was hoping to see a table not unlike jcalgtest for different cards, showing green/red/unknown status for various things :)

I'll see how to run this for cards you did not use...
