### ISSUE TITLE
ECTester For BN254

### ISSUE THREAD

**Issue by base0010** [crocs-muni/ECTester#19]
Has anyone actually been able to instantiate BN254 on a card. The curve parameters are mentioned for the reader. But params (FP,  A, B, R, ) are not present in the hardcoded version in the applet.
Cheers

**Comment by J08nY** [comment]
Hey,
the BN254 parameters are in the data directory, concretely:
https://github.com/crocs-muni/ECTester/blob/master/src/cz/crcs/ectester/data/bn/bn254.csv
To use it, either copy them over from there (the format is described [here](https://github.com/crocs-muni/ECTester/blob/master/docs/FORMAT.md)) or if you want to use it in the CLI, use the `-nc,--named-curve <cat/id>` option with category `bn` and curve id `bn254`.
