### ISSUE TITLE
Points for the cofactor/composite tests do not lie on the specified curves.

### ISSUE THREAD

**Issue by vojtechsu** [crocs-muni/ECTester#27]
The generator point in [composite192_pq2](https://github.com/crocs-muni/ECTester/blob/master/common/src/main/resources/cz/crcs/ectester/data/composite/composite192_pq2.csv) does not lie on the curve. Same for [cofactor128p65535](https://github.com/crocs-muni/ECTester/blob/master/common/src/main/resources/cz/crcs/ectester/data/cofactor/cofactor128p65535.csv).

The public key point [pq/cofactor192/1](https://github.com/crocs-muni/ECTester/blob/0bc459385a67f0a0f09abda7c1c768fc14e20a5f/common/src/main/resources/cz/crcs/ectester/data/cofactor/keys.xml#L670C16-L670C27) does not lie on the curve [composite192_pq1](https://github.com/crocs-muni/ECTester/blob/master/common/src/main/resources/cz/crcs/ectester/data/composite/composite192_pq1.csv).

**Comment by vojtechsu** [comment]
For composite192_pq2 the generator can be: (0x16a5b79035a1e561aae737dc7f32f3c03d5f03f73bd405e4, 0x3ddad60cc20b136913dcab69a30e5b71e0bf11f859658524)

For cofactor128p65535 it can be:
(0x91e251594dab368b04d7dd6d9b99fdef, 0xa7da97b3ba62ac554f7202d4f0348133)

The public key point pq/cofactor192/1 can be:
0x28f5b96b08f9dbe661472dbf8e5925b944e42ac5fdfdb2da, 0x227e8b2a9b07d1cd67211d4b933bf43eefbb7140e5a65dca

**Comment by J08nY** [comment]
I fixed these. Did you check this systematically or just by accident?

**Comment by vojtechsu** [comment]
I only checked prime field curves used in the cofactor test.
